version: '3'

services:
  runtests:
    image: theblusky/teamtasks:backend
    volumes:
      - ../backend/:/tmp_backend/
    environment:
      - TZ=Europe/Paris
    links:
      - postgres
      - ldap
    working_dir: /tmp_backend/
    command: sh runtests.sh

  ldap:
    image: osixia/openldap:1.2.2
    volumes:
      - ../misc/ldap_tests/data:/var/lib/ldap
      - ../misc/ldap_tests/config:/etc/ldap/slapd.d
