version: '3'

services:
  frontend:
    image: theblusky/teamtasks:frontend
    build:
      context: ..
      dockerfile: Dockerfile-frontend
    links:
     - backend

  backend:
    image: theblusky/teamtasks:backend
    build:
      context: ..
      dockerfile: Dockerfile-backend
    environment:
      - TZ=Europe/Paris
    links:
      - postgres
    depends_on:
      - cron
    command: gunicorn teamtasks.wsgi -w 4 --preload --log-file - --access-logfile - --bind 0.0.0.0:8000

  cron:
    image: theblusky/teamtasks:backend
    build:
      context: ..
      dockerfile: Dockerfile-backend
    environment:
      - TZ=Europe/Paris
    links:
      - postgres
    command: sh cron.sh

  postgres:
    image: postgres:latest
    environment:
      - "POSTGRES_USER=teamtasks"
      - "POSTGRES_PASSWORD=teamtasks"
