# Generated by Django 2.1 on 2018-08-18 14:05

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    UserLevel = apps.get_model("gamification", "UserLevel")
    User = apps.get_model("core", "User")
    db_alias = schema_editor.connection.alias
    UserLevel.objects.using(db_alias).bulk_create(
        [
            UserLevel(level=1, xp=0, hp=5, teamtasks_user=user)
            for user in User.objects.using(db_alias).all()
        ]
    )


def reverse_func(apps, schema_editor):
    UserLevel = apps.get_model("gamification", "UserLevel")
    db_alias = schema_editor.connection.alias
    UserLevel.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [("core", "0003_auto_20180818_1605")]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("field", models.CharField(max_length=8)),
                ("message", models.TextField()),
                ("amount", models.IntegerField()),
                ("read", models.BooleanField(default=False)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="UserLevel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField(default=1)),
                ("xp", models.IntegerField(default=0)),
                ("hp", models.IntegerField(default=20)),
                (
                    "teamtasks_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_level",
                        to="core.User",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="notification",
            name="user_level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gamification.UserLevel"
            ),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
