export const API_USERS_STATUS_REQUEST = 'API_USERS_STATUS_REQUEST'
export const API_USERS_STATUS_SUCCESS = 'API_USERS_STATUS_SUCCESS'
export const API_USERS_STATUS_FAILURE = 'API_USERS_STATUS_FAILURE'

export const API_USERS_REGISTER_REQUEST = 'API_USERS_REGISTER_REQUEST'
export const API_USERS_REGISTER_SUCCESS = 'API_USERS_REGISTER_SUCCESS'
export const API_USERS_REGISTER_FAILURE = 'API_USERS_REGISTER_FAILURE'

export const API_USERS_LOGIN_REQUEST = 'API_USERS_LOGIN_REQUEST'
export const API_USERS_LOGIN_SUCCESS = 'API_USERS_LOGIN_SUCCESS'
export const API_USERS_LOGIN_FAILURE = 'API_USERS_LOGIN_FAILURE'

export const API_USERS_LOGOUT_REQUEST = 'API_USERS_LOGOUT_REQUEST'
export const API_USERS_LOGOUT_SUCCESS = 'API_USERS_LOGOUT_SUCCESS'
export const API_USERS_LOGOUT_FAILURE = 'API_USERS_LOGOUT_FAILURE'

export const API_USERS_LIST_REQUEST = 'API_USERS_LIST_REQUEST'
export const API_USERS_LIST_SUCCESS = 'API_USERS_LIST_SUCCESS'
export const API_USERS_LIST_FAILURE = 'API_USERS_LIST_FAILURE'

export const API_TEAMS_CREATE_REQUEST = 'API_TEAMS_CREATE_REQUEST'
export const API_TEAMS_CREATE_SUCCESS = 'API_TEAMS_CREATE_SUCCESS'
export const API_TEAMS_CREATE_FAILURE = 'API_TEAMS_CREATE_FAILURE'

export const API_TEAMS_ADDUSER_REQUEST = 'API_TEAMS_ADDUSER_REQUEST'
export const API_TEAMS_ADDUSER_SUCCESS = 'API_TEAMS_ADDUSER_SUCCESS'
export const API_TEAMS_ADDUSER_FAILURE = 'API_TEAMS_ADDUSER_FAILURE'

export const API_WORKDAYS_CREATE_REQUEST = 'API_WORKDAYS_CREATE_REQUEST'
export const API_WORKDAYS_CREATE_SUCCESS = 'API_WORKDAYS_CREATE_SUCCESS'
export const API_WORKDAYS_CREATE_FAILURE = 'API_WORKDAYS_CREATE_FAILURE'

export const API_WORKDAYS_LIST_REQUEST = 'API_WORKDAYS_LIST_REQUEST'
export const API_WORKDAYS_LIST_SUCCESS = 'API_WORKDAYS_LIST_SUCCESS'
export const API_WORKDAYS_LIST_FAILURE = 'API_WORKDAYS_LIST_FAILURE'

export const API_WORKDAYS_CURRENT_REQUEST = 'API_WORKDAYS_CURRENT_REQUEST'
export const API_WORKDAYS_CURRENT_SUCCESS = 'API_WORKDAYS_CURRENT_SUCCESS'
export const API_WORKDAYS_CURRENT_FAILURE = 'API_WORKDAYS_CURRENT_FAILURE'

export const API_WORKDAYS_VALIDATEPLANNING_REQUEST = 'API_WORKDAYS_VALIDATEPLANNING_REQUEST'
export const API_WORKDAYS_VALIDATEPLANNING_SUCCESS = 'API_WORKDAYS_VALIDATEPLANNING_SUCCESS'
export const API_WORKDAYS_VALIDATEPLANNING_FAILURE = 'API_WORKDAYS_VALIDATEPLANNING_FAILURE'

export const API_WORKDAYS_VALIDATEWORKING_REQUEST = 'API_WORKDAYS_VALIDATEWORKING_REQUEST'
export const API_WORKDAYS_VALIDATEWORKING_SUCCESS = 'API_WORKDAYS_VALIDATEWORKING_SUCCESS'
export const API_WORKDAYS_VALIDATEWORKING_FAILURE = 'API_WORKDAYS_VALIDATEWORKING_FAILURE'

export const API_TASKS_CREATE_REQUEST = 'API_TASKS_CREATE_REQUEST'
export const API_TASKS_CREATE_SUCCESS = 'API_TASKS_CREATE_SUCCESS'
export const API_TASKS_CREATE_FAILURE = 'API_TASKS_CREATE_FAILURE'

export const API_TASKS_UPDATE_REQUEST = 'API_TASKS_UPDATE_REQUEST'
export const API_TASKS_UPDATE_SUCCESS = 'API_TASKS_UPDATE_SUCCESS'
export const API_TASKS_UPDATE_FAILURE = 'API_TASKS_UPDATE_FAILURE'

export const API_TASKS_SUGGESTIONS_REQUEST = 'API_TASKS_SUGGESTIONS_REQUEST'
export const API_TASKS_SUGGESTIONS_SUCCESS = 'API_TASKS_SUGGESTIONS_SUCCESS'
export const API_TASKS_SUGGESTIONS_FAILURE = 'API_TASKS_SUGGESTIONS_FAILURE'

export const API_TASKS_REMOVESUGGESTION_REQUEST = 'API_TASKS_REMOVESUGGESTION_REQUEST'
export const API_TASKS_REMOVESUGGESTION_SUCCESS = 'API_TASKS_REMOVESUGGESTION_SUCCESS'
export const API_TASKS_REMOVESUGGESTION_FAILURE = 'API_TASKS_REMOVESUGGESTION_FAILURE'

export const ERROR_ADD = 'ERROR_ADD'
export const ERROR_FLUSH = 'ERROR_FLUSH'

export const PAGE_CHANGE = 'PAGE_CHANGE'

export const generateActionId = () => (
  [...Array(32).keys()].map(() => (
    'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'[Math.floor(Math.random() * 62)]
  )).join('')
)
