# Generated by Django 2.1 on 2018-08-10 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=32)),
                ("comments_planning", models.TextField(blank=True, default="")),
                ("comments_validation", models.TextField(blank=True, default="")),
                ("done", models.BooleanField(default=False)),
                ("planned", models.BooleanField()),
                ("progress", models.IntegerField(default=-1)),
                ("suggest", models.BooleanField(default=True)),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("slack_url", models.CharField(default="", max_length=128)),
                ("slack_channel_public", models.CharField(default="", max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slack_name", models.CharField(default="", max_length=32)),
                ("is_admin", models.BooleanField(default=False)),
                ("level", models.IntegerField(default=1)),
                ("xp", models.IntegerField(default=0)),
                ("hp", models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name="WorkDay",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("planned_at", models.DateTimeField(default=None, null=True)),
                ("validated_at", models.DateTimeField(default=None, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.User"
                    ),
                ),
            ],
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="user",
            name="current_workday",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.WorkDay",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="django_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teamtasks_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="team",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.Team",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.User"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="workday",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.WorkDay"
            ),
        ),
    ]
