# Generated by Django 2.1 on 2018-08-18 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0002_auto_20180814_1902")]

    operations = [
        migrations.RemoveField(model_name="user", name="hp"),
        migrations.RemoveField(model_name="user", name="level"),
        migrations.RemoveField(model_name="user", name="xp"),
    ]
