# Generated by Django 2.1 on 2018-08-26 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0004_auto_20180824_1502")]

    operations = [
        migrations.RemoveField(model_name="team", name="slack_channel_public"),
        migrations.RemoveField(model_name="team", name="slack_url"),
        migrations.RemoveField(model_name="user", name="slack_name"),
    ]
