# Generated by Django 2.1 on 2018-08-26 11:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):  # pragma: no cover
    TeamSlack = apps.get_model("slack", "TeamSlack")
    Team = apps.get_model("core", "Team")
    db_alias = schema_editor.connection.alias
    TeamSlack.objects.using(db_alias).bulk_create(
        [TeamSlack(team=team) for team in Team.objects.using(db_alias).all()]
    )


def reverse_func(apps, schema_editor):  # pragma: no cover
    TeamSlack = apps.get_model("slack", "TeamSlack")
    db_alias = schema_editor.connection.alias
    TeamSlack.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [("core", "0005_auto_20180826_1324")]

    operations = [
        migrations.CreateModel(
            name="TeamSlack",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activated", models.BooleanField(default=False)),
                ("url", models.CharField(default="", max_length=512)),
                ("channel", models.CharField(default="", max_length=64)),
                ("users", django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_slack",
                        to="core.Team",
                    ),
                ),
            ],
        )
    ]
